import type { AgentDefinition } from "../shared/types"

const ALL_AGENTS: AgentDefinition[] = [
  // ─── MANAGEMENT ───
  {
    id: "pm",
    name: "PM",
    role: "Product Owner + Manager",
    model: "DeepSeek-V.4Pro",
    mode: "primary",
    category: "management",
    description: "Product vision, PRD, backlog, stakeholder management",
    scope: "Hanya PM yang bisa approve scope change",
    guard: "PRD creation, backlog grooming, sprint planning, stakeholder",
    tools: ["write", "read", "task", "call_agent", "http_api"],
    triggers: ["prd", "backlog", "vision", "roadmap", "scope", "stakeholder"],
    priority: 1,
  },
  {
    id: "scrum-master",
    name: "SM",
    role: "Scrum Master",
    model: "DeepSeek-V.4Pro",
    mode: "primary",
    category: "management",
    description: "Sprint flow, ceremony facilitation, blocker removal",
    scope: "Hanya SM yang breakdown stories & assign",
    guard: "Sprint lifecycle, task breakdown, assign, tracking",
    tools: ["task", "call_agent", "write", "read", "session_list"],
    triggers: ["sprint", "ceremony", "standup", "retro", "blocker"],
    priority: 2,
  },
  {
    id: "delivery-pm",
    name: "Delivery PM",
    role: "Delivery Manager",
    model: "DeepSeek-V.4Pro",
    mode: "primary",
    category: "management",
    description: "Timeline, resource, risk, reporting",
    scope: "Reporting & escalation",
    guard: "Delivery tracking, milestone, status report",
    tools: ["write", "read", "http_api", "session_list"],
    triggers: ["milestone", "deadline", "status", "delivery", "timeline"],
    priority: 3,
  },

  // ─── ANALYSIS ───
  {
    id: "ba",
    name: "BA",
    role: "Business Analyst",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "analysis",
    description: "Business requirements, PRD refinement, impact analysis",
    scope: "Impact analysis kena BA dulu",
    guard: "PRD writing, BRD, requirement analysis",
    tools: ["write", "read", "call_agent"],
    triggers: ["requirement", "brd", "impact", "process"],
    priority: 4,
  },
  {
    id: "system-analyst",
    name: "System Analyst",
    role: "System Analyst",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "analysis",
    description: "System design, TSD, flow diagrams",
    scope: "Teknis detail dari TSD",
    guard: "TSD creation, UML, ERD, sequence diagrams",
    tools: ["write", "read"],
    triggers: ["tsd", "flow", "diagram", "system design", "uml"],
    priority: 5,
  },
  {
    id: "architect",
    name: "Architect",
    role: "Solutions Architect",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "analysis",
    description: "Architecture decisions, ADRs",
    scope: "Design decision approval",
    guard: "Tech stack, architecture decision, ADR",
    tools: ["write", "read", "call_agent"],
    triggers: ["architecture", "adr", "tech stack", "decision"],
    priority: 6,
  },

  // ─── DESIGN ───
  {
    id: "ui-ux",
    name: "UI/UX",
    role: "UI/UX Designer",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "design",
    description: "User interface & experience design",
    scope: "Design output, validasi dengan PM",
    guard: "Wireframe, prototype, design system, usability",
    tools: ["write", "read"],
    triggers: ["design", "ui", "ux", "wireframe", "figma"],
    priority: 7,
  },

  // ─── DEVELOPMENT ───
  {
    id: "fe",
    name: "FE",
    role: "Frontend Engineer",
    model: "DeepSeek-V.4Pro",
    mode: "primary",
    category: "development",
    description: "UI implementation with React/Vue/Next.js",
    scope: "Hanya kerja dari user story, tolak request luar scope",
    guard: "React/Vue, component, styling, API integration",
    tools: ["write", "read", "grep", "glob", "http_api", "call_agent"],
    triggers: ["fe", "frontend", "ui", "component", "page"],
    priority: 8,
  },
  {
    id: "be",
    name: "BE",
    role: "Backend Engineer",
    model: "DeepSeek-V.4Pro",
    mode: "primary",
    category: "development",
    description: "Server-side logic, API development",
    scope: "Hanya kerja dari user story, forward ke SM kalo ada request baru",
    guard: "API, business logic, auth, caching",
    tools: ["write", "read", "grep", "glob", "http_api", "db_query", "call_agent"],
    triggers: ["be", "backend", "api", "endpoint", "service"],
    priority: 9,
  },
  {
    id: "mobile",
    name: "Mobile",
    role: "Mobile Developer",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "development",
    description: "Mobile apps (iOS/Android) with Flutter/React Native",
    scope: "Mobile scope only",
    guard: "Flutter/React Native implementation",
    tools: ["write", "read", "grep", "glob", "http_api"],
    triggers: ["mobile", "app", "ios", "android", "flutter"],
    priority: 10,
  },
  {
    id: "fullstack",
    name: "Full Stack",
    role: "Full Stack Engineer",
    model: "DeepSeek-V.4Pro",
    mode: "primary",
    category: "development",
    description: "End-to-end feature development",
    scope: "Jembatan antara FE & BE",
    guard: "Full features, FE+BE+DB",
    tools: ["write", "read", "grep", "glob", "http_api", "db_query"],
    triggers: ["fullstack", "full stack", "end-to-end", "feature"],
    priority: 11,
  },
  {
    id: "api-dev",
    name: "API Dev",
    role: "API Developer",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "development",
    description: "API design & implementation (REST/GraphQL/gRPC)",
    scope: "API contracts & versioning",
    guard: "REST/GraphQL/gRPC, OpenAPI",
    tools: ["write", "read", "http_api"],
    triggers: ["api", "endpoint", "rest", "graphql", "openapi"],
    priority: 12,
  },
  {
    id: "dba",
    name: "DBA",
    role: "Database Administrator",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "development",
    description: "Database management, schema, migration, optimization",
    scope: "DB changes wajib lewat DBA",
    guard: "DB schema, migration, query optimization",
    tools: ["db_query", "write", "read"],
    triggers: ["db", "database", "query", "migration", "schema", "sql"],
    priority: 13,
  },
  {
    id: "security-eng",
    name: "Security Eng",
    role: "Security Engineer",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "development",
    description: "Application security, vulnerability fix",
    scope: "Security review wajib sebelum production",
    guard: "Security testing, vulnerability fix, auth",
    tools: ["write", "read", "grep", "glob"],
    triggers: ["security", "vulnerability", "owasp", "csrf", "xss"],
    priority: 14,
  },
  {
    id: "perf-eng",
    name: "Perf Eng",
    role: "Performance Engineer",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "development",
    description: "Performance optimization and testing",
    scope: "Performance gate sebelum rilis",
    guard: "Load test, profiling, optimization",
    tools: ["write", "read", "http_api"],
    triggers: ["performance", "slow", "load", "benchmark", "optimize"],
    priority: 15,
  },

  // ─── DATA ───
  {
    id: "data-eng",
    name: "Data Eng",
    role: "Data Engineer",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "data",
    description: "Data pipeline, ETL/ELT, warehouse",
    scope: "Data flow via Data Engineer",
    guard: "Data pipeline, warehouse, ETL",
    tools: ["write", "read", "db_query", "http_api"],
    triggers: ["data pipeline", "etl", "elt", "spark", "airflow"],
    priority: 16,
  },
  {
    id: "data-sci",
    name: "Data Sci",
    role: "Data Scientist",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "data",
    description: "ML modeling, analytics, experimentation",
    scope: "Model validation wajib",
    guard: "Model development, analysis",
    tools: ["write", "read", "db_query"],
    triggers: ["ml", "model", "prediction", "analytics", "training"],
    priority: 17,
  },

  // ─── QUALITY ───
  {
    id: "qa",
    name: "QA",
    role: "Quality Assurance",
    model: "DeepSeek-V.4Pro",
    mode: "primary",
    category: "quality",
    description: "Testing, validation, bug reporting",
    scope: "TIDAK ADA YANG BISA MERILIS TANPA QA APPROVAL",
    guard: "Test plan, test case, automation test, UAT",
    tools: ["write", "read", "http_api", "call_agent"],
    triggers: ["test", "qa", "uat", "regression", "bug"],
    priority: 18,
  },

  // ─── INFRASTRUCTURE & OPS ───
  {
    id: "devops",
    name: "DevOps",
    role: "DevOps Engineer",
    model: "DeepSeek-V.4Pro",
    mode: "primary",
    category: "infra-ops",
    description: "CI/CD, infrastructure automation, Docker/K8s",
    scope: "Pipeline changes lewat DevOps",
    guard: "Pipeline, Docker, Kubernetes, IaC",
    tools: ["write", "read", "ssh_exec", "http_api", "call_agent"],
    triggers: ["devops", "ci/cd", "docker", "kubernetes", "terraform"],
    priority: 19,
  },
  {
    id: "cloud-eng",
    name: "Cloud Eng",
    role: "Cloud Engineer",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "infra-ops",
    description: "Cloud platform management (AWS/GCP/Azure)",
    scope: "Cloud cost & security",
    guard: "AWS/GCP/Azure, cloud resources",
    tools: ["write", "read", "http_api", "ssh_exec"],
    triggers: ["cloud", "aws", "gcp", "azure", "s3", "lambda"],
    priority: 20,
  },
  {
    id: "network-admin",
    name: "Network Admin",
    role: "Network Administrator",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "infra-ops",
    description: "Network infrastructure, firewall, VPN",
    scope: "Network changes wajib change request",
    guard: "Network config, firewall, VPN",
    tools: ["ssh_exec", "ping_test", "traceroute"],
    triggers: ["network", "vlan", "firewall", "dns", "vpn"],
    priority: 21,
  },
  {
    id: "sre",
    name: "SRE",
    role: "Site Reliability Engineer",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "infra-ops",
    description: "Reliability, monitoring, incident response",
    scope: "On-call escalation",
    guard: "SLO/SLI, monitoring, incident response",
    tools: ["http_api", "ssh_exec", "write", "read"],
    triggers: ["slo", "sli", "incident", "reliability", "monitoring"],
    priority: 22,
  },
  {
    id: "config-mgr",
    name: "Config Mgr",
    role: "Configuration Manager",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "infra-ops",
    description: "Configuration management, CMDB, drift detection",
    scope: "Config changes wajib approval",
    guard: "CMDB, config standardization, drift detection",
    tools: ["write", "read", "grep", "glob"],
    triggers: ["config", "configuration", "cmdb", "drift"],
    priority: 23,
  },
  {
    id: "it-support",
    name: "IT Support",
    role: "IT Support",
    model: "DeepSeek-V.4Pro",
    mode: "primary",
    category: "infra-ops",
    description: "First-line IT support, ticket triage",
    scope: "L1 issue only, escalate ke Engineer kalo kompleks",
    guard: "Ticket triage, password reset, basic troubleshooting",
    tools: ["read", "write", "call_agent"],
    triggers: ["help", "support", "ticket", "issue", "error", "problem"],
    priority: 24,
  },
  {
    id: "release-mgr",
    name: "Release Mgr",
    role: "Release Manager",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "infra-ops",
    description: "Release coordination, versioning, changelog",
    scope: "Release gak jalan tanpa approval",
    guard: "Release plan, versioning, change log",
    tools: ["write", "read", "call_agent", "task"],
    triggers: ["release", "version", "tag", "changelog", "go-live"],
    reportingTo: "scrum-master",
    priority: 25,
  },

  // ─── GOVERNANCE ───
  {
    id: "tech-lead",
    name: "Tech Lead",
    role: "Tech Lead",
    model: "DeepSeek-V.4Pro",
    mode: "primary",
    category: "governance",
    description: "Technical oversight, code review, standards",
    scope: "Code quality gate",
    guard: "Code review, tech direction, standard",
    tools: ["write", "read", "grep", "glob", "call_agent"],
    triggers: ["review", "tech lead", "code quality", "standard"],
    priority: 26,
  },
  {
    id: "it-compliance",
    name: "IT Compl",
    role: "IT Compliance / Auditor",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "governance",
    description: "Regulatory compliance, audit (ISO, SOC, GDPR)",
    scope: "Compliance gate sebelum rilis",
    guard: "ISO, SOC, GDPR, compliance audit",
    tools: ["write", "read"],
    triggers: ["compliance", "audit", "iso", "gdpr", "policy"],
    priority: 27,
  },
  {
    id: "ciso",
    name: "CISO",
    role: "CISO",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "governance",
    description: "Security policy, risk assessment, data protection",
    scope: "Keamanan adalah prioritas utama",
    guard: "Security policy, risk assessment",
    tools: ["write", "read", "call_agent"],
    triggers: ["ciso", "security policy", "risk assessment", "data protection"],
    priority: 28,
  },
  {
    id: "enterprise-arch",
    name: "Enterp Arch",
    role: "Enterprise Architect",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "governance",
    description: "Enterprise architecture strategy, portfolio roadmap",
    scope: "Strategic alignment",
    guard: "Tech portfolio, roadmap, strategy",
    tools: ["write", "read"],
    triggers: ["enterprise", "strategy", "portfolio", "roadmap"],
    priority: 29,
  },

  // ─── OTHER ───
  {
    id: "tech-writer",
    name: "Tech Writer",
    role: "Technical Writer",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "support",
    description: "Documentation, user manual, release notes",
    scope: "Documentation quality",
    guard: "Developer docs, user manual, release notes",
    tools: ["write", "read"],
    triggers: ["docs", "documentation", "manual", "guide", "readme"],
    priority: 30,
  },
  {
    id: "it-asset-mgr",
    name: "IT Asset Mgr",
    role: "IT Asset Manager",
    model: "DeepSeek-V.4Pro",
    mode: "subagent",
    category: "support",
    description: "Asset lifecycle management, license tracking",
    scope: "Asset tracking & compliance",
    guard: "Hardware/software inventory, license",
    tools: ["write", "read"],
    triggers: ["asset", "inventory", "license", "hardware"],
    priority: 31,
  },
]

export function getAgentById(id: string): AgentDefinition | undefined {
  return ALL_AGENTS.find((a) => a.id === id)
}

export function getAgentsByCategory(category: string): AgentDefinition[] {
  return ALL_AGENTS.filter((a) => a.category === category)
}

export function getAgentsByMode(mode: "primary" | "subagent"): AgentDefinition[] {
  return ALL_AGENTS.filter((a) => a.mode === mode)
}

export function getAllAgents(): AgentDefinition[] {
  return ALL_AGENTS
}

export function findAgentsByTrigger(text: string): AgentDefinition[] {
  const lower = text.toLowerCase()
  return ALL_AGENTS.filter((a) => a.triggers.some((t) => lower.includes(t)))
}
